#!/bin/sh
# Clean WRF data
cleaner -maxfiles 4 '_wrf_.*_surface.sqd' /smartmet/data/wrf
cleaner -maxfiles 4 '_wrf_.*_pressure.sqd' /smartmet/data/wrf
cleaner -maxfiles 2 '_wrf_.*_surface.sqd' /smartmet/editor/in
cleaner -maxfiles 2 '_wrf_.*_pressure.sqd' /smartmet/editor/in

# Clean incoming WRF data older than 1 day (24 * 60 min)
find /smartmet/data/incoming/wrf -type f -mmin +$((24 * 60)) -delete
find /smartmet/data/incoming/wrf -mindepth 2 -type d -empty -delete
